# Generated by Django 5.2.2 on 2025-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
