# Generated by Django 5.2.2 on 2025-06-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_is_premium'),
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='magazine.magazineissue'),
        ),
    ]
