# Generated by Django 5.2.2 on 2025-06-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_access',
            field=models.BooleanField(default=False),
        ),
    ]
