# Generated by Django 5.2.2 on 2025-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_has_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('READER', 'Reader'), ('AUTHOR', 'Author'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Admin')], default='READER', max_length=10),
        ),
    ]
