# Generated by Django 5.2.2 on 2025-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_magazinepurchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazineissue',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
